# Generated by Django 5.1.1 on 2024-09-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_miexamen_answers_response_and_more'),
        ('examenes', '0003_alter_pregunta_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='miexamen',
            name='pregunta',
            field=models.ManyToManyField(blank=True, null=True, to='examenes.pregunta'),
        ),
    ]
