# Generated by Django 5.1.1 on 2024-09-28 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_miexamen_pregunta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(default='')),
                ('fecha_up', models.DateTimeField(auto_now_add=True)),
                ('fecha_re', models.DateTimeField(blank=True, null=True)),
                ('visto', models.BooleanField(default=False)),
                ('respuesta', models.TextField(default='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'managed': True,
            },
        ),
    ]
