# Generated by Django 5.1.1 on 2024-09-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_alter_pregunta_imgage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='text',
            field=models.TextField(),
        ),
    ]
