# Generated by Django 5.1.1 on 2024-10-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_alter_pregunta_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='has_latex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='has_latex',
            field=models.BooleanField(default=False),
        ),
    ]
