# Generated by Django 5.1.1 on 2024-10-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_pregunta_has_latex_respuesta_has_latex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='text',
            field=models.TextField(),
        ),
    ]
