# Generated by Django 5.1.1 on 2024-10-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0005_alter_pregunta_answer_alter_respuesta_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['date'], 'verbose_name_plural': 'respuestas'},
        ),
    ]
